### ISSUE TITLE
publish the latest cookbook to supermarket

### ISSUE THREAD

**Issue by akadoya** [evertrue/ntp_cluster-cookbook#13]
Hi, apparently cookbook in Chef supermarket is not up to date.
Could you publish the latest v3.0.0 to supermarket?

**Comment by jeffbyrnes** [comment]
Sure thing!

**Comment by jeffbyrnes** [comment]
@akadoya I’ve published all the missing version to Supermarket.

@eherot if you’ve still got admin rights here, it’d be swell to grant me contrib status, so I can deal w/ issues & push code if needed.

**Comment by akadoya** [comment]
Thanks!
