### ISSUE TITLE
Initial Convergence Fails b/c of INIT

### ISSUE THREAD

**Issue by EdHurtig** [evertrue/ntp_cluster-cookbook#3]
This check might be a bit too strict or needs a bit of a delay

```
Running handlers:
10.99.112.247 [2015-10-16T02:14:44+00:00] ERROR: Running exception handlers
10.99.112.247   - Raven::Chef::SentryHandler
10.99.112.247 Running handlers complete
10.99.112.247 [2015-10-16T02:14:45+00:00] ERROR: Exception handlers complete
10.99.112.247 Chef Client failed. 541 resources updated in 04 minutes 15 seconds
10.99.112.247 [2015-10-16T02:14:46+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
10.99.112.247 [2015-10-16T02:14:46+00:00] ERROR: execute[verify ntp pool connectivity] (ntp_cluster::default line 40) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
10.99.112.247 ---- Begin output of ! /usr/bin/ntpq -p | grep "\.INIT\." ----
10.99.112.247 STDOUT: blue.1e400.net  .INIT.          16 u    -   64    0    0.000    0.000   0.000
10.99.112.247  mirror          .INIT.          16 u    -   64    0    0.000    0.000   0.000
10.99.112.247  F-Current.sjela .INIT.          16 u    -   64    0    0.000    0.000   0.000
10.99.112.247  172.82.134.51   .INIT.          16 u    -   64    0    0.000    0.000   0.000
10.99.112.247  juniperberry.ca .INIT.          16 u    -   64    0    0.000    0.000   0.000
10.99.112.247 STDERR:
10.99.112.247 ---- End output of ! /usr/bin/ntpq -p | grep "\.INIT\." ----
```

**Comment by EdHurtig** [comment]
I just logged into the box and everything was a'ok.  server was hooked up with the zk servers perfectly

**Comment by jeffbyrnes** [comment]
Kicking this over to @eherot, as he wired up this check. There was some concern this might happen.

**Comment by eherot** [comment]
Order appears to be a problem here considering that the listed ntp servers are not the ones that the cookbook is supposed to be setting up...

**Comment by EdHurtig** [comment]
Indeed, this check needs to run after the bro service restart

**Comment by EdHurtig** [comment]
Which is a delayed notification... which did get run after the execute resource failed

**Comment by EdHurtig** [comment]
```
node['ntp']['conf_restart_immediate']
```

**Comment by eherot** [comment]
...I wonder what else that would break.

Actually the bigger question for me is: Even with the misconfigured servers, why was it unable to sync the clocks? Presumably it should have had working Internet access. Perhaps it was indeed just taking a while? It would be interesting to see that whole Chef in a Gist with debug enabled.

**Comment by EdHurtig** [comment]
There is a delay while the connections with the ntp servers Initialize `INIT`

**Comment by EdHurtig** [comment]
Force syncing the clocks is a way to cut down on that init time

**Comment by eherot** [comment]
Yeah but if you do that they'll sync with every Chef run (which also means sudden changes instead of gradual slewing)

**Comment by EdHurtig** [comment]
yeah that's why I said force the sync only on first run...  However, look into that `node['ntp']['conf_restart_immediate']` attribute... that WILL solve this issue

**Comment by eherot** [comment]
Right, but possibly by causing others (like several restarts in one Chef run). Also if INIT takes a few seconds after a restart, it won't solve it.

Possibly a better option would be to have some retries on the execute command with a 1 second delay between each.

**Comment by EdHurtig** [comment]
retries could work. I'm not sure if INIT still takes a few seconds with our internal pool because there are only 3 servers to check in with

**Comment by eherot** [comment]
You really want to count on that?

**Comment by EdHurtig** [comment]
no I was going to check it out though out of curiosity

**Comment by eherot** [comment]
It seems like the kind of thing that would be notoriously hard to test (and likely to work more in a test environment than in some real life scenarios).

**Comment by EdHurtig** [comment]
or on a stage machine that i'm using for testing...

**Comment by EdHurtig** [comment]
but yeah go with the retries

**Comment by eherot** [comment]
That would be my suggestion unless your tests show that there's a better way. I'll let you decide what you want to do.

**Comment by EdHurtig** [comment]
I will be in later today

**Comment by EdHurtig** [comment]
can't test right now

**Comment by EdHurtig** [comment]
So lets settle on retries

**Comment by eherot** [comment]
lol.

**Comment by EdHurtig** [comment]
yep

**Comment by EdHurtig** [comment]
I'm _pretty_ sure this is fixed

**Comment by eherot** [comment]
We have had zero problems with it since the retries were added.

**Comment by EdHurtig** [comment]
excellent
