### ISSUE TITLE
Sync Clocks on first converge

### ISSUE THREAD

**Issue by EdHurtig** [evertrue/ntp_cluster-cookbook#4]
The best time to hard-sync the clocks is at first convergence.  The ntp cookbook has a attribute for this.  We should consider setting this attribute on first converge.

Might also solve #3 as a side effect

https://github.com/gmiranda23/ntp/blob/master/recipes/default.rb#L92-L104

**Comment by EdHurtig** [comment]
@eherot I can take assignment on this if you want

**Comment by EdHurtig** [comment]
Investigated this and due to the fact that `ntpd` is started with the `-g` argument which allows it's first adjustment to be a large jump, and given the fact that the service restarts right after the config is updated to point at the internal pool, we can be confident that upon initial convergence, the ntp daemon will hard sync the box.  

It will also hard sync whenever the ntp service is restarted regardless of chef... meaning that any reboots of the node will incur a hard sync... which is good

**Comment by jeffbyrnes** [comment]
@EdHurtig @eherot @mgreene are we sure that a hard/big sync is a good thing for all instances? E.g., the C* nodes.

**Comment by EdHurtig** [comment]
When the node is initially converging this MUST happen... it is a really bad thing if it doesn't

When the node reboots... same thing it is much better to try and jump the clock before anything is really running yet instead of letting the node run with a very bad clock that is ever so slowly adjusting itself

**Comment by mgreene** [comment]
So the timestamps going into the Cassandra database are now being generated from both the Cassandra ring itself and client nodes, depending on the workload. 

Pretty much every node in our system needs to behave in a similar way at this point.

**Comment by EdHurtig** [comment]
That is exactly what this tries to ensure

**Comment by mgreene** [comment]
@EdHurtig is this a blocking operation or is it open to race conditions?

**Comment by EdHurtig** [comment]
possibly open to race conditions... it depends on what run level the apps services start on
